### ISSUE TITLE
How does App Service start Node?

### ISSUE THREAD

**Issue by simkessy** [anvilation/azure-webapp-typescript-express#1]
So how does the app run. By that I mean, locally I need to run node dist/index.js to get my application to start and listen. 

When you push it to the app service, does it automatically know to do this? If not how do you get the node service to start in app services?

I created an app, deployed through DevOps Pipelines but when I go to my site it just shows me the default Welcome Screen.

**Comment by anvilation** [comment]
Hi There, 

Sorry I missed this one. 

- To run this service locally you can run ```npm run dev```
- in the companion [medium article ](https://levelup.gitconnected.com/node-typescript-azure-web-apps-what-could-go-wrong-a-lessons-learnt-guide-2def97a59f1f) my Azure DevOp pipelines copy the dist and azure folders to the same location and then publish the combined packaged to Azure App Service

Keep in mind that there might be an issue with the 64 bit version of node, So you might need to copy the version of node seperately. 

Hope this helps
